FROM fedora:latest
LABEL maintainer="Xiaofeng Wang" \
      email="xiaofwan@redhat.com" \
      baseimage="Fedora:latest" \
      description="A welder-web RPM builder container running on Fedora"

ARG NODE_FILE

RUN dnf install -y make cmake rpm-build gnupg tar xz curl jq nodejs && dnf clean all

WORKDIR /welder
CMD ["make", "rpm"]
