FROM welder/web-nodejs:latest
LABEL maintainer="Xiaofeng Wang" \
      email="xiaofwan@redhat.com" \
      baseimage="Fedora:latest" \
      description="A welder-web end to end test runner container running on Fedora"

# Install xvfb to simulate framebuffer for nightmare.js
# Install electorn dependency
RUN dnf --setopt=deltarpm=0 --verbose install -y xorg-x11-server-Xvfb which libXScrnSaver \
clang dbus-devel gtk2-devel libnotify-devel libgnome-keyring-devel xorg-x11-server-utils \
libcap-devel cups-devel libXtst-devel alsa-lib-devel libXrandr-devel GConf2-devel nss-devel

CMD ["xvfb-run", "-a", "-s", "-screen 0 1024x768x24", "npm", "run", "test"]

COPY . /welder-web/

# install dependencies needed by the main application
WORKDIR /welder-web/
RUN npm install

# install dependencies needed by the tests
WORKDIR /welder-web/test/end-to-end/
RUN npm install --only=production

ENTRYPOINT ["/welder-web/test/end-to-end/entrypoint.sh"]
