FROM fedora:latest
LABEL maintainer="Xiaofeng Wang" \
      email="xiaofwan@redhat.com" \
      baseimage="Fedora:latest" \
      description="A welder-web RPM builder container running on Fedora"

ARG NODE_FILE

RUN dnf install -y make cmake rpm-build gnupg tar xz curl jq && dnf clean all

RUN echo 'PATH=/usr/local/bin/:$PATH' >> /etc/bashrc

COPY $NODE_FILE .
RUN tar -xJf $NODE_FILE -C /usr/local --strip-components=1

WORKDIR /welder
CMD ["make", "rpm"]
